In [1]:
import pandas as pd
import atoti as tt

from sqlalchemy import create_engine

Welcome to Atoti 0.9.14!

By using this community edition, you agree with the license available at https://docs.activeviam.com/products/atoti/python-sdk/latest/eula.html.
Browse the official documentation at https://docs.activeviam.com/products/atoti/python-sdk.
Join the community at https://www.atoti.io/register.

Atoti collects telemetry data, which is used to help understand how to improve the product.
If you don't wish to send usage data, you can request a trial license at https://www.atoti.io/evaluation-license-request.

You can hide this message by setting the `ATOTI_HIDE_EULA_MESSAGE` environment variable to True.

In [2]:
DB_URL = "postgresql://neondb_owner:npg_zh8nMebyx4GI@ep-lively-paper-apc3pjfg.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require"

engine = create_engine(DB_URL)

print("Koneksi Neon berhasil")

Koneksi Neon berhasil

Ambil Data PostgreSQL

In [3]:
df_fact = pd.read_sql(
    "SELECT * FROM fact_market",
    engine
)

df_dim = pd.read_sql(
    "SELECT * FROM dim_waktu",
    engine
)

print("Fact Shape :", df_fact.shape)
print("Dim Shape :", df_dim.shape)

df_fact.head()

Fact Shape : (2858, 5)
Dim Shape : (2858, 5)

   id_waktu     btc_close  btc_volume  fed_rate tren_pasar_btc
0  20180131  10233.000000    0.047865      1.41        Bearish
1  20180201   9232.001175    0.094380      1.41        Bearish
2  20180202   8849.999994    0.097364      1.41        Bearish
3  20180203   9199.999443    0.308737      1.41        Bearish
4  20180204   8117.000002    0.613943      1.41        Bearish

Tambah Kolom Analisis

In [4]:
df_fact["is_anomaly"] = (
    (df_fact["btc_close"] > 65000) |
    (df_fact["btc_close"] < 20000)
)

df_fact["kategori_volume"] = pd.cut(
    df_fact["btc_volume"],
    bins=3,
    labels=["Rendah", "Sedang", "Tinggi"]
)

df_fact.head()

,id_waktu,btc_close,btc_volume,fed_rate,tren_pasar_btc,is_anomaly,kategori_volume
0,20180131,10233.000000,0.047865,1.41,Bearish,True,Rendah
1,20180201,9232.001175,0.094380,1.41,Bearish,True,Rendah
2,20180202,8849.999994,0.097364,1.41,Bearish,True,Rendah
3,20180203,9199.999443,0.308737,1.41,Bearish,True,Rendah
4,20180204,8117.000002,0.613943,1.41,Bearish,True,Rendah

Buat session atoti

In [5]:
session = tt.Session.start()

session

Buat tabel atoti

In [6]:
tabel_dimensi = session.read_pandas(
    df_dim,
    table_name="dim_waktu",
    keys=["id_waktu"]
)

tabel_fakta = session.read_pandas(
    df_fact,
    table_name="fact_market",
    keys=["id_waktu"]
)

print("Tabel berhasil dibuat")

Tabel berhasil dibuat

Join fact dan dimension

In [7]:
tabel_fakta.join(
    tabel_dimensi,
    tabel_fakta["id_waktu"] == tabel_dimensi["id_waktu"]
)

print("Join berhasil")

Join berhasil

buat cube

In [8]:
cube = session.create_cube(
    tabel_fakta,
    "Market_DataMart"
)

cube

buat measures

In [11]:
m = cube.measures

m["Rata-rata BTC"] = tt.agg.mean(
    tabel_fakta["btc_close"]
)

m["Rata-rata FED Rate"] = tt.agg.mean(
    tabel_fakta["fed_rate"]
)

m["Total Volume BTC"] = tt.agg.sum(
    tabel_fakta["btc_volume"]
)

m["Harga BTC Maksimum"] = tt.agg.max(
    tabel_fakta["btc_close"]
)

m["Harga BTC Minimum"] = tt.agg.min(
    tabel_fakta["btc_close"]
)

In [13]:
corr = df_fact["btc_close"].corr(
    df_fact["fed_rate"]
)

print("Korelasi BTC vs FED =", round(corr, 4))

Korelasi BTC vs FED = 0.4432

In [14]:
cube

In [15]:
session.link

http://localhost:49465